application: cyanogenmodstats
version: 4
runtime: python
api_version: 1

handlers:
- url: /
  script: handler.py
  
- url: /submit
  script: handler.py
  
- url: /tasks/.*
  script: tasks.py
