application: cyanogenmodstats
version: 5
runtime: python
api_version: 1

handlers:
- url: /
  script: pages/main.py
  
- url: /submit
  script: pages/submit.py

- url: /static
  static_dir: static
