application: cyanogenmodstats
version: 12
runtime: python
api_version: 1

handlers:
- url: /
  script: pages/main.py
  
- url: /ajax/.*
  script: pages/ajax.py
  
- url: /tasks/.*
  script: pages/tasks.py
  login: admin
  
- url: /submit
  script: pages/submit.py

- url: /static
  static_dir: static
